"""Environment file generation utilities."""

from pathlib import Path
from typing import Optional

from .config import discover_services, get_project_root


def get_common_env_path(root: Path) -> Path:
    """Get shared env fragment path."""
    return root / "env" / "common.env"


def get_service_env_path(root: Path, service_id: str) -> Path:
    """Get env fragment path for a service."""
    return root / "services" / service_id / "env.example"


def collect_env_fragments(
    profiles: list[str],
    root: Optional[Path] = None,
) -> tuple[list[Path], list[str], list[str]]:
    """Collect env fragments for selected profiles.

    Returns (fragments, selected_profiles, missing_profiles).
    """
    if root is None:
        root = get_project_root()

    services = discover_services(root)
    selected = profiles or list(services.keys())

    missing = [profile for profile in selected if profile not in services]

    fragments: list[Path] = []
    common = get_common_env_path(root)
    if common.exists():
        fragments.append(common)

    for profile in selected:
        if profile in services:
            env_path = get_service_env_path(root, profile)
            if env_path.exists():
                fragments.append(env_path)

    return fragments, selected, missing


def generate_env_file(
    profiles: list[str],
    output_path: Path,
    root: Optional[Path] = None,
) -> tuple[list[str], list[Path]]:
    """Generate an env file from fragments."""
    if root is None:
        root = get_project_root()

    fragments, selected, missing = collect_env_fragments(profiles, root=root)
    if missing:
        raise ValueError(f"Unknown profiles: {', '.join(missing)}")

    lines: list[str] = [
        "# Generated by ./ecosystem env",
        f"# Profiles: {', '.join(selected) if selected else 'none'}",
        "",
    ]

    for fragment in fragments:
        rel_path = fragment.relative_to(root)
        lines.append(f"# --- {rel_path} ---")
        content = fragment.read_text().rstrip()
        if content:
            lines.append(content)
        lines.append("")

    output_path.write_text("\n".join(lines).rstrip() + "\n")
    return selected, fragments
